# Generated by Django 6.0.6 on 2026-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='item',
            field=models.JSONField(default={'product': 'product_name', 'quantity': 0, 'unit_price': 0.0}),
        ),
    ]
