# Generated by Django 6.0.6 on 2026-07-11 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_remove_quotation_emailaddress_remove_quotation_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_ca_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 12)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won  ', 'Won'), ('lost', 'Lost')], default='pending', max_length=20),
        ),
    ]
