# Generated by Django 6.0.6 on 2026-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0004_remove_quotation_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(blank=True, choices=[('on-grid', 'On-Grid'), ('off-grid', 'Off-Grid'), ('hybrid', 'Hybrid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=20),
        ),
    ]
