# Generated by Django 6.0.6 on 2026-07-13 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0005_alter_quotation_project_type_alter_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBOM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('on-grid', 'On-Grid'), ('hybrid', 'Hybrid'), ('off-grid', 'Off-Grid')], default='on-grid', max_length=20)),
                ('system_size_kw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 14)),
        ),
    ]
