# Generated by Django 6.0.6 on 2026-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0006_systembom_alter_quotation_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembom',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
