# Generated by Django 6.0.6 on 2026-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0007_systembom_profit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembom',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='systembom',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
