# Generated by Django 6.0.6 on 2026-07-16 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0008_systembom_base_cost_systembom_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='bom_snapshot',
            field=models.JSONField(blank=True, help_text='Stores structural snapshot data for BOM matching packages.', null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 16)),
        ),
        migrations.AlterField(
            model_name='systembom',
            name='system_size_kw',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
