# Generated by Django 6.0.6 on 2026-07-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0009_quotation_bom_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='bom_snapshot',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bom_snapshot', models.JSONField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_auth.quotation')),
            ],
        ),
    ]
