# Generated by Django 6.0.6 on 2026-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0010_remove_quotation_bom_snapshot_remove_quotation_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
