# Generated by Django 6.0.6 on 2026-07-18 20:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0012_alter_quotation_quotation_date_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 19)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / NEFT / RTGS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('paid_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core_auth.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
