# Generated by Django 6.0.6 on 2026-07-19 18:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0013_alter_quotation_quotation_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 20)),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_source_type', models.CharField(blank=True, choices=[('existing_customer', 'Existing Customer'), ('employee', 'Employee'), ('vendor_dealer', 'Vendor / Dealer'), ('walk_in', 'Walk-in'), ('online_ad', 'Online / Ad'), ('other', 'Other'), ('website', 'Website')], max_length=20)),
                ('referral_name', models.CharField(blank=True, help_text='Name of the person/entity who referred this lead', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('project_type', models.CharField(blank=True, choices=[('on-grid', 'On-Grid'), ('off-grid', 'Off-Grid'), ('hybrid', 'Hybrid')], max_length=20)),
                ('estimated_system_size', models.CharField(blank=True, max_length=50)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_done', 'Site Visit Done'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=25)),
                ('lost_reason', models.CharField(blank=True, choices=[('price', 'Price too high'), ('competitor', 'Went with a competitor'), ('not_ready', 'Not ready yet'), ('no_response', 'Stopped responding'), ('other', 'Other')], max_length=20)),
                ('lost_reason_notes', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='core_auth.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core_auth.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
