# Generated by Django 6.0.6 on 2026-07-20 20:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0014_alter_quotation_quotation_date_lead_leadnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General Note'), ('call', 'Call Log'), ('metting', 'Meeting Outcome'), ('site_visit', 'Site Visit Outcome'), ('status_change', 'Status Change')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='Quotation_date',
            field=models.DateField(default=datetime.date(2026, 7, 21)),
        ),
    ]
