# Generated by Django 6.0.6 on 2026-07-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0015_leadnote_created_by_leadnote_note_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='source_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='core_auth.lead'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General Note'), ('call', 'Call Log'), ('meeting', 'Meeting Outcome'), ('site_visit', 'Site Visit Outcome'), ('status_change', 'Status Change')], default='general', max_length=20),
        ),
    ]
